"""Regenerate LEADERBOARD.md from the scorecards on disk.

    python corpus/leaderboard.py
    python corpus/leaderboard.py --check     # fail if the file is out of date

Generated, never hand-kept, for the reason every generated artifact in this
repository is generated: a table maintained by hand next to the data it
summarises drifts, and this one would drift in a direction that flatters whoever
maintains it.

WHAT IT REFUSES TO DO. It never orders detectors by a single number. Recall
without a false-alarm rate is half a result, and a leaderboard sorted on recall
rewards a detector that flags everything. Rows are sorted by split then by name,
and every row carries recall, blind-spot recall, false alarms and coverage
together or it does not appear.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CARDS = HERE / "scorecards"
OUT = HERE / "LEADERBOARD.md"

HEADER = """# dinocorpus leaderboard

Generated by `python corpus/leaderboard.py` from `corpus/scorecards/`. Do not
edit by hand.

**Read all four columns or none of them.** Recall alone rewards a detector that
flags everything, which is why the false-alarm rate sits beside it and why
nothing here is sorted by score. `blind` is recall on defect classes the
detector has no rule for, under STRICT scoring: it must name an item the defect
was actually planted in, so an unrelated warning firing by chance is not a
catch.

Recall figures are UPPER BOUNDS. The corpus items are synthetic and cleaner than
real benchmark items; see [basepool.py](basepool.py).

A score means nothing without its split. Splits and their label commitments:
[SPLITS.md](SPLITS.md).
"""

FOOTER = """
## Submitting

Run your detector over a split's instances and send the JSON. Format, scoring
rules and what counts as a catch: [README.md](README.md#submitting-a-detector).
Submissions are scored with `corpus/score.py`, which refuses malformed files
rather than publishing a 0% caused by a typo.
"""


def rows() -> list[dict]:
    if not CARDS.is_dir():
        return []
    out = []
    for path in sorted(CARDS.glob("*.json")):
        card = json.loads(path.read_text(encoding="utf-8"))
        out.append(card)
    return sorted(out, key=lambda c: (c.get("split", ""), c.get("detector", "")))


def render(cards: list[dict]) -> str:
    lines = [HEADER, ""]
    if not cards:
        lines.append("No scorecards yet. `python corpus/score.py --json "
                     "corpus/scorecards/dinostomp.json` writes the first one.")
        return "\n".join(lines) + "\n" + FOOTER

    def pct(x):
        return "-" if x is None else f"{x:.1%}"

    lines.append("| detector | split | covered | blind (strict) | false alarms | answered |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for c in cards:
        answered = c.get("answered")
        coverage = ("all" if answered is None or answered == c.get("n_scored")
                    else f"{answered} of {c.get('n_scored')}")
        lines.append(
            f"| {c.get('detector', '?')} | `{c.get('split', '?')}` "
            f"| {pct(c.get('recall_covered'))} | {pct(c.get('recall_blind_spot_strict'))} "
            f"| {pct(c.get('false_alarm_rate_on_clean'))} | {coverage} |")
    lines.append("")
    lines.append("`covered` is recall on defect classes the detector has a rule for; `blind` is "
                 "recall on classes it does not, which is the column that says whether a detector "
                 "generalises past its own rule list.")
    return "\n".join(lines) + "\n" + FOOTER


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if LEADERBOARD.md is out of date")
    args = ap.parse_args()

    cards = rows()
    body = render(cards)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != body:
            print("LEADERBOARD.md is out of date; run `python corpus/leaderboard.py`",
                  file=sys.stderr)
            return 1
        print(f"leaderboard current: {len(cards)} detector(s)")
        return 0

    OUT.write_text(body, encoding="utf-8", newline="\n")
    print(f"{len(cards)} detector(s) -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
